Implement CAS Manager idle shutdown

diff --git a/terraform-deployments/modules/centos-gfx-vm/centos-gfx-provisioning.sh.tmpl b/terraform-deployments/modules/centos-gfx-vm/centos-gfx-provisioning.sh.tmpl
--- a/terraform-deployments/modules/centos-gfx-vm/centos-gfx-provisioning.sh.tmpl
+++ b/terraform-deployments/modules/centos-gfx-vm/centos-gfx-provisioning.sh.tmpl
@@ -11,14 +11,30 @@ INST_LOG_PATH="/var/log/teradici/agent/"
 INST_LOG_FILE="/var/log/teradici/agent/install.log"
 DETAILED_LOG_FILE="/var/log/teradici/agent/detailed.log"
 
-PCOIP_REGISTRATION_CODE=${pcoip_registration_code}
-AD_SERVICE_ACCOUNT_PASSWORD=${ad_service_account_password}
-AD_SERVICE_ACCOUNT_USERNAME=${ad_service_account_username}
-DOMAIN_NAME=${domain_name}
-DOMAIN_CONTROLLER_IP=${domain_controller_ip}
-APPLICATION_ID=${application_id}
-AAD_CLIENT_SECRET=${aad_client_secret}
-TENANT_ID=${tenant_id}
+ENABLE_AUTO_SHUTDOWN=${enable_workstation_idle_shutdown}
+AUTO_SHUTDOWN_IDLE_TIMER=${minutes_idle_before_shutdown}
+CPU_POLLING_INTERVAL=${minutes_cpu_polling_interval}
+
+retry() {
+    local retries=0
+    local max_retries=3
+    until [[ $retries -ge $max_retries ]]
+    do  
+    # Break if command succeeds, or log then retry if command fails.
+        $@ && break || {
+
+            log "--> Failed to run command. $@"
+            log "--> Retries left... $(( $max_retries - $retries ))"
+            ((retries++))
+            sleep 10;
+        }
+    done
+
+    if [[ $retries -eq $max_retries ]]
+    then
+        return 1
+    fi
+}
 
 log() {
     local message="$1"
@@ -26,16 +42,20 @@ log() {
 }
 
 get_credentials() {
-    if [[ -z "$TENANT_ID" ]]; then
+    set +x
+    if [[ -z "${tenant_id}" ]]; then
         log "Not getting secrets from Azure Key Vault. Exiting get_credentials..."
+
+        PCOIP_REGISTRATION_CODE=${pcoip_registration_code}
+        AD_SERVICE_ACCOUNT_PASSWORD=${ad_service_account_password}
+
     else
-        set +x
         log "Getting secrets from Azure Key Vault..."
-        ACCESS_TOKEN=$(curl -X POST -d "grant_type=client_credentials&client_id=$APPLICATION_ID&client_secret=$AAD_CLIENT_SECRET&resource=https%3A%2F%2Fvault.azure.net" https://login.microsoftonline.com/$TENANT_ID/oauth2/token | jq ".access_token" -r)
+        ACCESS_TOKEN=$(curl -X POST -d "grant_type=client_credentials&client_id=${application_id}&client_secret=${aad_client_secret}&resource=https%3A%2F%2Fvault.azure.net" https://login.microsoftonline.com/${tenant_id}/oauth2/token | jq ".access_token" -r)
         PCOIP_REGISTRATION_CODE=$(curl -X GET -H "Authorization: Bearer $ACCESS_TOKEN" -H "Content-Type: application/json" --url "$PCOIP_REGISTRATION_CODE?api-version=2016-10-01" | jq -r '.value')
         AD_SERVICE_ACCOUNT_PASSWORD=$(curl -X GET -H "Authorization: Bearer $ACCESS_TOKEN" -H "Content-Type: application/json" --url "$AD_SERVICE_ACCOUNT_PASSWORD?api-version=2016-10-01" | jq -r '.value')
-        set -x
     fi
+    set -x
 }
 
 exit_and_restart() {
@@ -212,15 +232,43 @@ install_pcoip_agent() {
     fi
 }
 
-# Join domain
+install_idle_shutdown() {
+    log "--> Installing idle shutdown..."
+    mkdir /tmp/idleShutdown
+
+    retry wget "https://raw.githubusercontent.com/teradici/deploy/master/remote-workstations/new-agent-vm/Install-Idle-Shutdown.sh" -O /tmp/idleShutdown/Install-Idle-Shutdown-raw.sh
+
+    awk '{ sub("\r$", ""); print }' /tmp/idleShutdown/Install-Idle-Shutdown-raw.sh > /tmp/idleShutdown/Install-Idle-Shutdown.sh && chmod +x /tmp/idleShutdown/Install-Idle-Shutdown.sh
+
+    log "--> Setting auto shutdown idle timer to $AUTO_SHUTDOWN_IDLE_TIMER minutes..."
+    INSTALL_OPTS="--idle-timer $AUTO_SHUTDOWN_IDLE_TIMER"
+    if [[ "$ENABLE_AUTO_SHUTDOWN" = "false" ]]; then
+        INSTALL_OPTS="$INSTALL_OPTS --disabled"
+    fi
+
+    retry /tmp/idleShutdown/Install-Idle-Shutdown.sh $INSTALL_OPTS
+
+    exitCode=$?
+    if [[ $exitCode -ne 0 ]]; then
+        log "--> ERROR: Failed to install idle shutdown."
+        exit 1
+    fi
+
+    if [[ $CPU_POLLING_INTERVAL -ne 15 ]]; then
+        log "--> Setting CPU polling interval to $CPU_POLLING_INTERVAL minutes..."
+        sed -i "s/OnUnitActiveSec=15min/OnUnitActiveSec=$${CPU_POLLING_INTERVAL}min/g" /etc/systemd/system/CAMIdleShutdown.timer.d/CAMIdleShutdown.conf
+        systemctl daemon-reload
+    fi
+}
+
 join_domain()
 {
     local dns_record_file="dns_record"
     if [[ ! -f "$dns_record_file" ]]
     then
-        log "--> DOMAIN NAME: $DOMAIN_NAME"
-        log "--> USERNAME: $AD_SERVICE_ACCOUNT_USERNAME"
-        log "--> DOMAIN CONTROLLER: $DOMAIN_CONTROLLER_IP"
+        log "--> DOMAIN NAME: ${domain_name}"
+        log "--> USERNAME: ${ad_service_account_username}"
+        log "--> DOMAIN CONTROLLER: ${domain_controller_ip}"
         log "--> HOSTNAME: $HOSTNAME"
 
         VM_NAME=$(hostname)
@@ -237,11 +285,11 @@ join_domain()
         counter=0
 
         log "$_"
-        log "--> Wait for AD account $AD_SERVICE_ACCOUNT_USERNAME@$DOMAIN_NAME to be available"
-        until ldapwhoami -H ldap://$DOMAIN_CONTROLLER_IP -D $AD_SERVICE_ACCOUNT_USERNAME@$DOMAIN_NAME -w $AD_SERVICE_ACCOUNT_PASSWORD -o nettimeout=3 > /dev/null 2>&1
+        log "--> Wait for AD account ${ad_service_account_username}@${domain_name} to be available"
+        until ldapwhoami -H ldap://${domain_controller_ip} -D ${ad_service_account_username}@${domain_name} -w $AD_SERVICE_ACCOUNT_PASSWORD -o nettimeout=3 > /dev/null 2>&1
         do
             counter=$(($counter + 1))
-            log "$AD_SERVICE_ACCOUNT_USERNAME@$DOMAIN_NAME not available yet, retrying in 10 seconds..."
+            log "${ad_service_account_username}@${domain_name} not available yet, retrying in 10 seconds..."
             sleep 10
             if [ $counter -ge 360 ]; then
                 log "--> Failed to join domain controller after $counter tries."
@@ -264,28 +312,28 @@ join_domain()
             return 106
         fi
 
-        log "--> Joining the domain '$DOMAIN_NAME'..."
+        log "--> Joining the domain '${domain_name}'..."
         local retries=10
 
         set +x
         while true
         do
-            echo $AD_SERVICE_ACCOUNT_PASSWORD | realm join --user="$AD_SERVICE_ACCOUNT_USERNAME@$DOMAIN_NAME" "$DOMAIN_NAME" --verbose >&2
+            echo $AD_SERVICE_ACCOUNT_PASSWORD | realm join --user="${ad_service_account_username}@${domain_name}" "${domain_name}" --verbose >&2
             
             local rc=$?
             if [[ $rc -eq 0 ]]
             then
-                log "--> Successfully joined domain '$DOMAIN_NAME'."
+                log "--> Successfully joined domain '${domain_name}'."
                 break
             fi
 
             if [ $retries -eq 0 ]
             then
-                log "--> ERROR: Failed to join domain '$DOMAIN_NAME'."
+                log "--> ERROR: Failed to join domain '${domain_name}'."
                 return 106
             fi
 
-            log "--> ERROR: Failed to join domain '$DOMAIN_NAME'. $retries retries remaining..."
+            log "--> ERROR: Failed to join domain '${domain_name}'. $retries retries remaining..."
             retries=$((retries-1))
             sleep 60
         done
@@ -295,29 +343,21 @@ join_domain()
         sed -i '$ a\dyndns_update = True\ndyndns_ttl = 3600\ndyndns_refresh_interval = 43200\ndyndns_update_ptr = True\nldap_user_principal = nosuchattribute' /etc/sssd/sssd.conf
         sed -c -i "s/\\(use_fully_qualified_names *= *\\).*/\\1False/" /etc/sssd/sssd.conf
         sed -c -i "s/\\(fallback_homedir *= *\\).*/\\1\\/home\\/%u/" /etc/sssd/sssd.conf
-        domainname "$VM_NAME.$DOMAIN_NAME"
-        echo "%$DOMAIN_NAME\\\\Domain\\ Admins ALL=(ALL) ALL" > /etc/sudoers.d/sudoers
+        domainname "$VM_NAME.${domain_name}"
+        echo "%${domain_name}\\\\Domain\\ Admins ALL=(ALL) ALL" > /etc/sudoers.d/sudoers
 
         log "--> Registering with DNS"
-        DOMAIN_UPPER=$(echo "$DOMAIN_NAME" | tr '[:lower:]' '[:upper:]')
+        DOMAIN_UPPER=$(echo "${domain_name}" | tr '[:lower:]' '[:upper:]')
         IP_ADDRESS=$(hostname -I | grep -Eo '10.([0-9]*\.){2}[0-9]*')
         set +x
-        echo $AD_SERVICE_ACCOUNT_PASSWORD | kinit "$AD_SERVICE_ACCOUNT_USERNAME"@"$DOMAIN_UPPER"
+        echo $AD_SERVICE_ACCOUNT_PASSWORD | kinit "${ad_service_account_username}"@"$DOMAIN_UPPER"
         set -x
         touch "$dns_record_file"
-        echo "server $DOMAIN_CONTROLLER_IP" > "$dns_record_file"
-        echo "update add $VM_NAME.$DOMAIN_NAME 600 a $IP_ADDRESS" >> "$dns_record_file"
+        echo "server ${domain_controller_ip}" > "$dns_record_file"
+        echo "update add $VM_NAME.${domain_name} 600 a $IP_ADDRESS" >> "$dns_record_file"
         echo "send" >> "$dns_record_file"
         nsupdate -g "$dns_record_file"
     fi
-}
-
-# Open up firewall for PCoIP Agent. By default eth0 is in firewall zone "public"
-update_firewall() {
-    log "--> Adding 'pcoip-agent' service to public firewall zone..."
-    firewall-offline-cmd --zone=public --add-service=pcoip-agent
-    systemctl enable firewalld
-    systemctl start firewalld
 }
 
 # A flag to indicate if this is run from reboot
@@ -410,9 +450,9 @@ else
 
     install_pcoip_agent
 
-    log "--> Installation is complete!"
+    install_idle_shutdown
 
-    update_firewall
+    log "--> Installation is complete!"
     
     sed -i '$ d' /etc/rc.local
 
