Install USB dependencies to support  additional USB devices

diff --git a/terraform-deployments/modules/centos-gfx-vm/centos-gfx-provisioning.sh.tmpl b/terraform-deployments/modules/centos-gfx-vm/centos-gfx-provisioning.sh.tmpl
--- a/terraform-deployments/modules/centos-gfx-vm/centos-gfx-provisioning.sh.tmpl
+++ b/terraform-deployments/modules/centos-gfx-vm/centos-gfx-provisioning.sh.tmpl
@@ -202,6 +202,13 @@ install_pcoip_agent() {
         log "--> Getting Teradici PCoIP agent repo..."
         wget --retry-connrefused --tries=3 --waitretry=5 -P /etc/yum.repos.d $PCOIP_AGENT_REPO_URL
 
+        log "--> Installing USB dependencies..."
+        retry "yum install -y usb-vhci"
+        if [ $? -ne 0 ]; then
+            log "--> Warning: Failed to install usb-vhci."
+        fi
+        log "--> usb-vhci successfully installed."
+
         log "--> Installing PCoIP graphics agent..."
         yum -y install pcoip-agent-graphics
         if [ $? -ne 0 ]; then
diff --git a/terraform-deployments/modules/centos-std-vm/centos-std-provisioning.sh.tmpl b/terraform-deployments/modules/centos-std-vm/centos-std-provisioning.sh.tmpl
--- a/terraform-deployments/modules/centos-std-vm/centos-std-provisioning.sh.tmpl
+++ b/terraform-deployments/modules/centos-std-vm/centos-std-provisioning.sh.tmpl
@@ -76,6 +76,13 @@ install_pcoip_agent() {
         log "--> Get Teradici PCoIP agent repo"
         wget --retry-connrefused --tries=3 --waitretry=5 -O /etc/yum.repos.d/pcoip.repo $PCOIP_AGENT_REPO_URL
 
+        log "--> Installing USB dependencies..."
+        retry "yum install -y usb-vhci"
+        if [ $? -ne 0 ]; then
+            log "--> Warning: Failed to install usb-vhci."
+        fi
+        log "--> usb-vhci successfully installed."
+
         log "--> Install PCoIP standard agent ..."
         dnf -y install pcoip-agent-standard
         if [ $? -ne 0 ]; then
