Add domain join retry to CentOS script

diff --git a/terraform-deployments/modules/centos-std-vm/centos-std-provisioning.sh.tmpl b/terraform-deployments/modules/centos-std-vm/centos-std-provisioning.sh.tmpl
--- a/terraform-deployments/modules/centos-std-vm/centos-std-provisioning.sh.tmpl
+++ b/terraform-deployments/modules/centos-std-vm/centos-std-provisioning.sh.tmpl
@@ -149,21 +149,32 @@ join_domain()
             return 106
         fi
 
-        log "--> Joining the domain '${domain_name}'"
-        if [[ -n "$OU" ]]
-        then
+        log "--> Joining the domain '${domain_name}'..."
+        local retries=10
+
+        set +x
+        while true
+        do
             echo "${ad_service_account_password}" | realm join --user="${ad_service_account_username}@${domain_name}" "${domain_name}" --verbose >&2
-        else
-            echo "${ad_service_account_password}" | realm join --user="${ad_service_account_username}" "${domain_name}" >&2
-        fi
-        exitCode=$?
-        if [[ $exitCode -eq 0 ]]
-        then
-            log "--> Joined Domain '${domain_name}'"
-        else
-            log "--> Failed to join Domain '${domain_name}' and OU '$OU'"
-            return 106
-        fi
+            
+            local rc=$?
+            if [[ $rc -eq 0 ]]
+            then
+                log "--> Successfully joined domain '${domain_name}'."
+                break
+            fi
+
+            if [ $retries -eq 0 ]
+            then
+                log "--> ERROR: Failed to join domain '${domain_name}'."
+                return 106
+            fi
+
+            log "--> ERROR: Failed to join domain '${domain_name}'. $retries retries remaining..."
+            retries=$((retries-1))
+            sleep 60
+        done
+        set -x
 
         log "--> Configuring settings"
         sed -i '$ a\dyndns_update = True\ndyndns_ttl = 3600\ndyndns_refresh_interval = 43200\ndyndns_update_ptr = True\nldap_user_principal = nosuchattribute' /etc/sssd/sssd.conf
