Clean up scripts for Linux machines

diff --git a/terraform-deployments/modules/centos-std-vm/centos-std-provisioning.sh.tmpl b/terraform-deployments/modules/centos-std-vm/centos-std-provisioning.sh.tmpl
--- a/terraform-deployments/modules/centos-std-vm/centos-std-provisioning.sh.tmpl
+++ b/terraform-deployments/modules/centos-std-vm/centos-std-provisioning.sh.tmpl
@@ -12,14 +12,14 @@ DETAILED_LOG_FILE="/var/log/teradici/agent/detailed.log"
 PCOIP_AGENT_REPO_PUBKEY_URL="https://downloads.teradici.com/rhel/teradici.pub.gpg"
 PCOIP_AGENT_REPO_URL="https://downloads.teradici.com/rhel/pcoip.repo"
 
-pcoip_registration_code=${pcoip_registration_code}
-ad_service_account_password=${ad_service_account_password}
-ad_service_account_username=${ad_service_account_username}
-domain_name=${domain_name}
-domain_controller_ip=${domain_controller_ip}
-appID=${app_id}
-aadClientSecret=${aad_client_secret}
-tenantID=${tenant_id}
+PCOIP_REGISTRATION_CODE=${pcoip_registration_code}
+AD_SERVICE_ACCOUNT_PASSWORD=${ad_service_account_password}
+AD_SERVICE_ACCOUNT_USERNAME=${ad_service_account_username}
+DOMAIN_NAME=${domain_name}
+DOMAIN_CONTROLLER_IP=${domain_controller_ip}
+APPLICATION_ID=${application_id}
+AAD_CLIENT_SECRET=${aad_client_secret}
+TENANT_ID=${tenant_id}
 
 log() {
     local message="$1"
@@ -31,22 +31,14 @@ error_exit() {
 	exit 1
 }
 
-get_access_token() {
-    accessToken=`curl -X POST -d "grant_type=client_credentials&client_id=$1&client_secret=$2&resource=https%3A%2F%2Fvault.azure.net" https://login.microsoftonline.com/$3/oauth2/token`
-    token=$(echo $accessToken | jq ".access_token" -r)
-    json_map=`curl -X GET -H "Authorization: Bearer $token" -H "Content-Type: application/json" --url "$4?api-version=2016-10-01"`
-    value=$(echo $json_map | jq -r '.value')
-    echo "$value"
-}
-
 get_credentials() {
-    # Check if we need to get secrets from Azure Key Vault
-    if [[ -z "$tenantID" ]]; then
+    if [[ -z "$TENANT_ID" ]]; then
         log "Not getting secrets from Azure Key Vault. Exiting get_credentials..."
     else
-        log "Getting secrets from Azure Key Vault. Using the following passed variables: $2, $1, $3, $4, $5"
-        pcoip_registration_code=$(get_access_token $2 $1 $3 $4)
-        ad_service_account_password=$(get_access_token $2 $1 $3 $5)
+        log "Getting secrets from Azure Key Vault..."
+        ACCESS_TOKEN=$(curl -X POST -d "grant_type=client_credentials&client_id=$APPLICATION_ID&client_secret=$AAD_CLIENT_SECRET&resource=https%3A%2F%2Fvault.azure.net" https://login.microsoftonline.com/$TENANT_ID/oauth2/token | jq ".access_token" -r)
+        PCOIP_REGISTRATION_CODE=$(curl -X GET -H "Authorization: Bearer $ACCESS_TOKEN" -H "Content-Type: application/json" --url "$PCOIP_REGISTRATION_CODE?api-version=2016-10-01" | jq -r '.value')
+        AD_SERVICE_ACCOUNT_PASSWORD=$(curl -X GET -H "Authorization: Bearer $ACCESS_TOKEN" -H "Content-Type: application/json" --url "$AD_SERVICE_ACCOUNT_PASSWORD?api-version=2016-10-01" | jq -r '.value')
     fi
 }
 
@@ -73,7 +65,7 @@ install_pcoip_agent() {
         log "--> Registering PCoIP agent license..."
         n=0
         while true; do
-            /usr/sbin/pcoip-register-host --registration-code="$pcoip_registration_code" && break
+            /usr/sbin/pcoip-register-host --registration-code="$PCOIP_REGISTRATION_CODE" && break
             log "--> $?"
             n=$[$n+1]
 
@@ -95,10 +87,9 @@ join_domain()
     local dns_record_file="dns_record"
     if [[ ! -f "$dns_record_file" ]]
     then
-        log "--> DOMAIN NAME: ${domain_name}"
-        log "--> USERNAME: ${ad_service_account_username}"
-        log "--> PASSWORD: $ad_service_account_password"
-        log "--> DOMAIN CONTROLLER: ${domain_controller_ip}"
+        log "--> DOMAIN NAME: $DOMAIN_NAME"
+        log "--> USERNAME: $AD_SERVICE_ACCOUNT_USERNAME"
+        log "--> DOMAIN CONTROLLER: $DOMAIN_CONTROLLER_IP"
         log "--> HOSTNAME: $HOSTNAME"
 
         VM_NAME=$(hostname)
@@ -115,11 +106,11 @@ join_domain()
         counter=0
 
         log "$_"
-        log "--> Wait for AD account ${ad_service_account_username}@${domain_name} to be available"
-        until ldapwhoami -H ldap://${domain_controller_ip} -D ${ad_service_account_username}@${domain_name} -w "$${ad_service_account_password}" -o nettimeout=3 > /dev/null 2>&1
+        log "--> Wait for AD account $AD_SERVICE_ACCOUNT_USERNAME@$DOMAIN_NAME to be available"
+        until ldapwhoami -H ldap://$DOMAIN_CONTROLLER_IP -D $AD_SERVICE_ACCOUNT_USERNAME@$DOMAIN_NAME -w "$AD_SERVICE_ACCOUNT_PASSWORD" -o nettimeout=3 > /dev/null 2>&1
         do
             counter=$(($counter + 1))
-            log "${ad_service_account_username}@${domain_name} not available yet, retrying in 10 seconds..."
+            log "$AD_SERVICE_ACCOUNT_USERNAME@$DOMAIN_NAME not available yet, retrying in 10 seconds..."
             sleep 10
             if [ $counter -ge 360 ]; then
                 log "--> Failed to join domain controller after $counter tries."
@@ -142,28 +133,28 @@ join_domain()
             return 106
         fi
 
-        log "--> Joining the domain '${domain_name}'..."
+        log "--> Joining the domain '$DOMAIN_NAME'..."
         local retries=10
 
         set +x
         while true
         do
-            echo $ad_service_account_password | realm join --user="${ad_service_account_username}@${domain_name}" "${domain_name}" --verbose >&2
+            echo $AD_SERVICE_ACCOUNT_PASSWORD | realm join --user="$AD_SERVICE_ACCOUNT_USERNAME@$DOMAIN_NAME" "$DOMAIN_NAME" --verbose >&2
             
             local rc=$?
             if [[ $rc -eq 0 ]]
             then
-                log "--> Successfully joined domain '${domain_name}'."
+                log "--> Successfully joined domain '$DOMAIN_NAME'."
                 break
             fi
 
             if [ $retries -eq 0 ]
             then
-                log "--> ERROR: Failed to join domain '${domain_name}'."
+                log "--> ERROR: Failed to join domain '$DOMAIN_NAME'."
                 return 106
             fi
 
-            log "--> ERROR: Failed to join domain '${domain_name}'. $retries retries remaining..."
+            log "--> ERROR: Failed to join domain '$DOMAIN_NAME'. $retries retries remaining..."
             retries=$((retries-1))
             sleep 60
         done
@@ -173,16 +164,16 @@ join_domain()
         sed -i '$ a\dyndns_update = True\ndyndns_ttl = 3600\ndyndns_refresh_interval = 43200\ndyndns_update_ptr = True\nldap_user_principal = nosuchattribute' /etc/sssd/sssd.conf
         sed -c -i "s/\\(use_fully_qualified_names *= *\\).*/\\1False/" /etc/sssd/sssd.conf
         sed -c -i "s/\\(fallback_homedir *= *\\).*/\\1\\/home\\/%u/" /etc/sssd/sssd.conf
-        domainname "$VM_NAME.${domain_name}"
-        echo "%${domain_name}\\\\Domain\\ Admins ALL=(ALL) ALL" > /etc/sudoers.d/sudoers
+        domainname "$VM_NAME.$DOMAIN_NAME"
+        echo "%$DOMAIN_NAME\\\\Domain\\ Admins ALL=(ALL) ALL" > /etc/sudoers.d/sudoers
 
         log "--> Registering with DNS"
-        DOMAIN_UPPER=$(echo "${domain_name}" | tr '[:lower:]' '[:upper:]')
+        DOMAIN_UPPER=$(echo "$DOMAIN_NAME" | tr '[:lower:]' '[:upper:]')
         IP_ADDRESS=$(hostname -I | grep -Eo '10.([0-9]*\.){2}[0-9]*')
-        echo $ad_service_account_password | kinit "${ad_service_account_username}"@"$DOMAIN_UPPER"
+        echo $AD_SERVICE_ACCOUNT_PASSWORD | kinit "$AD_SERVICE_ACCOUNT_USERNAME"@"$DOMAIN_UPPER"
         touch "$dns_record_file"
-        echo "server ${domain_controller_ip}" > "$dns_record_file"
-        echo "update add $VM_NAME.${domain_name} 600 a $IP_ADDRESS" >> "$dns_record_file"
+        echo "server $DOMAIN_CONTROLLER_IP" > "$dns_record_file"
+        echo "update add $VM_NAME.$DOMAIN_NAME 600 a $IP_ADDRESS" >> "$dns_record_file"
         echo "send" >> "$dns_record_file"
         nsupdate -g "$dns_record_file"
     fi
@@ -245,11 +236,7 @@ if [ $? -ne 0 ]; then
     log "Failed to install jq"
 fi
 
-get_credentials $aadClientSecret $appID $tenantID $pcoip_registration_code $ad_service_account_password
-log "$domain_name ;; $domain_controller_ip"
-
-# log "Updating packages.."
-# yum update -y --exclude=WALinuxAgent
+get_credentials
 
 log "--> Install Linux GUI ..."
 yum -y groupinstall "GNOME Desktop" "Graphical Administration Tools"
