Add retry to GUI installation for CentOS scripts

diff --git a/terraform-deployments/modules/centos-std-vm/centos-std-provisioning.sh.tmpl b/terraform-deployments/modules/centos-std-vm/centos-std-provisioning.sh.tmpl
--- a/terraform-deployments/modules/centos-std-vm/centos-std-provisioning.sh.tmpl
+++ b/terraform-deployments/modules/centos-std-vm/centos-std-provisioning.sh.tmpl
@@ -35,10 +35,12 @@ get_credentials() {
     if [[ -z "$TENANT_ID" ]]; then
         log "Not getting secrets from Azure Key Vault. Exiting get_credentials..."
     else
+        set +x
         log "Getting secrets from Azure Key Vault..."
         ACCESS_TOKEN=$(curl -X POST -d "grant_type=client_credentials&client_id=$APPLICATION_ID&client_secret=$AAD_CLIENT_SECRET&resource=https%3A%2F%2Fvault.azure.net" https://login.microsoftonline.com/$TENANT_ID/oauth2/token | jq ".access_token" -r)
         PCOIP_REGISTRATION_CODE=$(curl -X GET -H "Authorization: Bearer $ACCESS_TOKEN" -H "Content-Type: application/json" --url "$PCOIP_REGISTRATION_CODE?api-version=2016-10-01" | jq -r '.value')
         AD_SERVICE_ACCOUNT_PASSWORD=$(curl -X GET -H "Authorization: Bearer $ACCESS_TOKEN" -H "Content-Type: application/json" --url "$AD_SERVICE_ACCOUNT_PASSWORD?api-version=2016-10-01" | jq -r '.value')
+        set -x
     fi
 }
 
@@ -170,7 +172,10 @@ join_domain()
         log "--> Registering with DNS"
         DOMAIN_UPPER=$(echo "$DOMAIN_NAME" | tr '[:lower:]' '[:upper:]')
         IP_ADDRESS=$(hostname -I | grep -Eo '10.([0-9]*\.){2}[0-9]*')
+
+        set +x
         echo $AD_SERVICE_ACCOUNT_PASSWORD | kinit "$AD_SERVICE_ACCOUNT_USERNAME"@"$DOMAIN_UPPER"
+        set -x
         touch "$dns_record_file"
         echo "server $DOMAIN_CONTROLLER_IP" > "$dns_record_file"
         echo "update add $VM_NAME.$DOMAIN_NAME 600 a $IP_ADDRESS" >> "$dns_record_file"
@@ -223,6 +228,9 @@ log "Starting dnf"
 systemctl enable dnf-automatic.timer
 systemctl start dnf-automatic.timer
 
+# A flag to check if a GUI is installed
+IS_GUI_INSTALLED=0
+
 log "--> Get epel-release"
 yum -y install epel-release
 if [ $? -ne 0 ]; then
@@ -238,10 +246,11 @@ fi
 
 get_credentials
 
-log "--> Install Linux GUI ..."
+log "--> Installing Linux GUI ..."
 yum -y groupinstall "GNOME Desktop" "Graphical Administration Tools"
 if [ $? -ne 0 ]; then
     log "Failed to install Linux GUI"
+    IS_GUI_INSTALLED=1
 fi
 
 log "--> Set default to graphical target"
@@ -250,6 +259,16 @@ systemctl set-default graphical.target
 join_domain
 
 install_pcoip_agent
+
+if [[ $IS_GUI_INSTALLED -eq 1 ]] 
+then
+    log "--> Retrying installation of Linux GUI ..."
+    yum -y groupinstall "GNOME Desktop" "Graphical Administration Tools"
+
+    if [ $? -ne 0 ]; then
+        log "Failed to install Linux GUI on the second attempt."
+    fi
+fi
 
 # Stage complete
 log "--> Installaion complete!"
